# Kconfig overlay for release builds
# Usage: west build -- -DEXTRA_CONF_FILE=prj_extra_release.conf -Dmcuboot_EXTRA_CONF_FILE=sysbuild/mcuboot_extra_release.conf

# Suppress logging
CONFIG_LOG=n
CONFIG_CONSOLE=n
