# RTT logging for MCUboot
CONFIG_USE_SEGGER_RTT=y
CONFIG_RTT_CONSOLE=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=n
CONFIG_LOG=y
CONFIG_LOG_MODE_MINIMAL=y
CONFIG_MCUBOOT_LOG_LEVEL_INF=y

# KMU key slots (dev + prod + backup)
CONFIG_BOOT_SIGNATURE_KMU_SLOTS=3
