# Workaround: disable memory guard to avoid false faults in application after boot
CONFIG_HW_STACK_PROTECTION=n

CONFIG_BOOT_WATCHDOG_FEED=n

CONFIG_PM_OVERRIDE_EXTERNAL_DRIVER_CHECK=y

# Without tickless kernel, SYSCOUNTER is not restored correctly after soft reset.
CONFIG_TICKLESS_KERNEL=y
