# Kconfig overlay for production build
# Usage: west build -- -DEXTRA_CONF_FILE=prj_extra_production.conf -Dmcuboot_EXTRA_CONF_FILE=$PWD/sysbuild/mcuboot_extra_production.conf -DSB_EXTRA_CONF_FILE=sysbuild_extra_production.conf

# Enable flash protection
CONFIG_FPROTECT=y
