# Kconfig fragment for Matter over Thread (replaces default of BTHome)
# Usage: west build -- -DEXTRA_CONF_FILE=prj_extra_matter.conf -DSB_EXTRA_CONF_FILE=sysbuild_extra_matter.conf

SB_CONFIG_MATTER=y
SB_CONFIG_MATTER_FACTORY_DATA_GENERATE=y
SB_CONFIG_PM_OVERRIDE_EXTERNAL_DRIVER_CHECK=n
SB_CONFIG_PM_EXTERNAL_FLASH_MCUBOOT_SECONDARY=n
