# Kconfig fragment for production build suitable for end-users
# Usage: west build -- -DEXTRA_CONF_FILE=prj_extra_production.conf -DSB_EXTRA_CONF_FILE=sysbuild_extra_production.conf

# Sign with the production key
SB_CONFIG_BOOT_SIGNATURE_KEY_FILE="keys/prod.pem"

# Prevent reading device's memory to protect device keys
SB_CONFIG_APPROTECT_LOCK=y
