CONFIG_GPIO=y
CONFIG_I2C=y
CONFIG_PINCTRL=y

# NPM1304 PMIC
CONFIG_MFD=y
CONFIG_WATCHDOG=y
CONFIG_LED=y
CONFIG_REGULATOR=y
CONFIG_SENSOR=y

# GRTC timer
CONFIG_NRF_GRTC_TIMER=y

# Bluetooth
CONFIG_BT=y
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_DEVICE_NAME="BL54L15u DevKit"
CONFIG_BT_PER_ADV_SYNC=y

# MCUboot
CONFIG_BOOTLOADER_MCUBOOT=y

# MCUmgr OTA DFU over BLE
CONFIG_MCUMGR=y
CONFIG_MCUMGR_TRANSPORT_BT=y
CONFIG_MCUMGR_TRANSPORT_BT_REASSEMBLY=y
CONFIG_BT_L2CAP_TX_MTU=247
CONFIG_BT_BUF_ACL_TX_SIZE=251
CONFIG_BT_BUF_ACL_RX_SIZE=251
CONFIG_MCUMGR_GRP_IMG=y
CONFIG_MCUMGR_GRP_OS=y
CONFIG_MCUMGR_GRP_OS_BOOTLOADER_INFO=y
CONFIG_IMG_MANAGER=y
CONFIG_IMG_ERASE_PROGRESSIVELY=y
CONFIG_STREAM_FLASH=y
CONFIG_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_CRC=y
CONFIG_NET_BUF=y
CONFIG_ZCBOR=y

# nRF Fuel Gauge (SoC estimation for LiPo via nPM1304)
CONFIG_NRF_FUEL_GAUGE=y
CONFIG_NRF_FUEL_GAUGE_VARIANT_SECONDARY_CELL=y

# Stack sizes
CONFIG_MAIN_STACK_SIZE=4096
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2304
